language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
addons:
  sonarcloud:
    organization: "dsaltares-github"
script:
  - npm install
  - npm run lint
  - npm run coverage
  - sonar-scanner
